# Generated by Django 3.1.1 on 2022-12-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20221129_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(max_length=64, null=True, verbose_name='编号'),
        ),
    ]
