# Generated by Django 3.1.1 on 2022-12-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20221209_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(blank=True, max_length=64, null=True, verbose_name='出版日期'),
        ),
    ]
