# Generated by Django 3.1.1 on 2022-12-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20221209_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(blank=True, default=2003, max_length=64, verbose_name='出版日期'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='translator',
            field=models.CharField(default=2, max_length=64, verbose_name='译者'),
            preserve_default=False,
        ),
    ]
