# Generated by Django 3.1.1 on 2022-12-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20221209_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(max_length=64, verbose_name='编号'),
        ),
    ]
