# Generated by Django 3.1.1 on 2022-12-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20221209_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='translator',
            field=models.CharField(max_length=64, null=True, verbose_name='译者'),
        ),
    ]
