# Generated by Django 3.1.1 on 2022-12-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20221209_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(max_length=64, null=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(blank=True, max_length=64, null=True, verbose_name='出版日期'),
        ),
        migrations.AlterField(
            model_name='book',
            name='translator',
            field=models.CharField(max_length=64, null=True, verbose_name='译者'),
        ),
    ]
